CREATE TABLE "guilds" (
	"id" text PRIMARY KEY NOT NULL,
	"prefix" varchar(5) DEFAULT '$' NOT NULL,
	"premium_tier" integer DEFAULT 1 NOT NULL,
	"autoroles" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"sticky_messages" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"starboard" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"autoresponders" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"welcome" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"leave" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"boost" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"logging" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"automod_log" text,
	"nuke" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"antinuke" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"antiraid" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"honeypot" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"jail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"warn_punishments" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"reaction_roles" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"button_roles" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"booster_roles" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"sticky_roles" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"fake_permissions" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"counting" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"confessions" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"leveling" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"automessages" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"autoplay" boolean DEFAULT false NOT NULL,
	"disabled_commands" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"custom_aliases" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"custom_avatar" text,
	"custom_banner" text,
	"name_style" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" text PRIMARY KEY NOT NULL,
	"balance" integer DEFAULT 0 NOT NULL,
	"lastfm" text,
	"premium" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
